### PR TITLE
Support for Rails 6.1

### PR DESCRIPTION
**Pull request by swelther**
This PR adds support for Rails 6.1. We have a project that still uses paperclip and want to add support for Rails 6.1.

### CODE REVIEW

**Comment by swelther** [comment]
Not sure why the travis build does not run 🤔 Is there anything I can or need to do?

**Comment by mherold** [comment]
Hi @sweither, thanks for your PR!

"Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on."

I think we would need to switch to e.g. github actions, AFAIK travis-ci.com has no free account for open source.

**Comment by swelther** [comment]
Ah I missed that one. The webpage on travis-ci.com still claims `Testing your open source projects is always 100% free!` :) 

Probably a maintainer of this Repo has to create an account there. Tell me if I can help somehow with this issue.

**Comment by mherold** [comment]
You're correct, it's possible, but one would have to set up billing and then request OSS credits by email (https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source). The process seems a bit involved compared to setting up GH Actions.  
I'll have a look at it.

**Comment by mherold** [comment]
Ok i just added GH actions for automated testing. Could you rebase your PR and add the corresponding new configuration to  the matrix in `.github/workflows/test.yml`? 

(Unfortunately we still also need the `.travis.yml` if we want to keep local tests via wwtd. )

**Comment by swelther** [comment]
Awesome, thank you :)

Rebased and pushed a modified version, but it seems like you need to approve before a workflow starts to run :)

**Comment by mherold** [comment]
Thanks! New version release upcoming ;-)

**Comment by swelther** [comment]
Awesome, thank you very much :)

**Pull request merged**
